[package]
name = "strata"
version = "0.1.0"
description = "A visual atlas for your codebase"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "strata_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
window-vibrancy = "0.8.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
uuid = { version = "1.27.0", features = ["v4"] }
tree-sitter = "0.27.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-javascript = "0.25.0"
ignore = "0.4.33"
rayon = "1.12.0"
regex = "1.13.1"
serde_yaml = "0.9.34"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
